---
- name: Enable or Disable SELinux
  hosts: all
  vars: 
    status: disabled
    tasks: 
    - name: change SELinux in configurstion file
      lineinfile: 
           path: /etc/selinux/config
           regexp: '^SELINUX='
           line: 'SELINUX={{ status }}'
           